[package]
name = "runtime"
version = "1.1.0"
authors = ["Interlay <contact@interlay.io>"]
edition = "2018"

[features]
default = []
testing-utils = [
    "tempdir",
    "interbtc",
    "interbtc-runtime",
    "rand",
    "subxt-client",
]
standalone-metadata = []
parachain-metadata-interlay = []
parachain-metadata-kintsugi = []
parachain-metadata-interlay-testnet = []
parachain-metadata-kintsugi-testnet = []

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "full"] }
async-trait = "0.1.40"
thiserror = "1.0"
serde_json = "1.0.71"
tokio = { version = "1.0", features = ["full"] }
backoff = { version = "0.3.0", features = ["tokio"] }
futures = "0.3.5"
clap = "3.1"
log = "0.4.0"
url = "2"
cfg-if = "1.0"
prometheus = { version = "0.12.0", features = ["process"] }

# Substrate dependencies
sp-arithmetic = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-version = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }

# Subxt dependencies
# https://github.com/interlay/subxt/tree/polkadot-v0.9.24
subxt = { package = "subxt", git = "https://github.com/interlay/subxt", rev = "cad1564b487f59c53840894607debf1aaae7a2f7" }
subxt-client = { package = "subxt-client", path = "./client", optional = true }

jsonrpsee = { version = "0.10.1", features = ["macros", "jsonrpsee-types", "client", "jsonrpsee-ws-client", "jsonrpsee-client-transport"] }

bitcoin = { path = "../bitcoin"}

# Dependencies for the testing utils for integration tests
tempdir = { version = "0.3.7", optional = true }
interbtc = { package = "interbtc-parachain", git = "https://github.com/interlay/interbtc", rev = "2ddb5eba6fdb42125805bf15d8a4caf30556e0ab", optional = true }
interbtc-runtime = { package = "testnet-kintsugi-runtime-parachain", git = "https://github.com/interlay/interbtc", rev = "2ddb5eba6fdb42125805bf15d8a4caf30556e0ab", optional = true }
rand = { version = "0.7", optional = true }

[dependencies.primitives]
git = "https://github.com/interlay/interbtc"
rev = "2ddb5eba6fdb42125805bf15d8a4caf30556e0ab"
package = "interbtc-primitives"

[dependencies.module-bitcoin]
git = "https://github.com/interlay/interbtc"
rev = "2ddb5eba6fdb42125805bf15d8a4caf30556e0ab"
package = "bitcoin"

[dependencies.module-btc-relay]
git = "https://github.com/interlay/interbtc"
rev = "2ddb5eba6fdb42125805bf15d8a4caf30556e0ab"
package = "btc-relay"

[dependencies.module-oracle-rpc-runtime-api]
git = "https://github.com/interlay/interbtc"
rev = "2ddb5eba6fdb42125805bf15d8a4caf30556e0ab"
package = "module-oracle-rpc-runtime-api"

[dev-dependencies]
runtime = { path = ".", features = ["testing-utils"] }
tempdir = "0.3.7"
env_logger = "0.8.3"